name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much detail as possible to help us understand your request.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: What is the feature you'd like to see?
      placeholder: e.g. Dark mode toggle
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature and how it would work.
      placeholder: A detailed explanation of the proposed feature or change
    validations:
      required: true