name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Short summary of the issue
      placeholder: e.g. Unexpected crash when clicking submit
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe what you observed. What did you expect to happen?
      placeholder: Describe the issue and expected behavior
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a clear sequence of steps to recreate the issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Observe error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Output or Screenshots
      description: Include error logs, stack traces, or screenshots if applicable
      render: shell

  - type: input
    id: environment
    attributes:
      label: Environment Info
      description: Provide any relevant system or version details (e.g. OS, browser, tool version)
      placeholder: e.g. Windows 11, Chrome 116, v2.3.1

